name: ai_shorts
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1  # requires NVIDIA GPU & drivers
  - ffmpeg
  - pip:
      - opencv-python
      - numpy
      - flask
      - tqdm
